export const GET_NOTE_TYPES = 'GET_NOTE_TYPES';
export const GET_LABELS = 'GET_LABELS';
export const GET_INSPIRATIONS = 'GET_INSPIRATIONS';

export const GET_NOTES = 'GET_NOTES';
export const CREATE_NOTE = 'CREATE_NOTE';
export const EDIT_NOTE = 'EDIT_NOTE';
export const DELETE_NOTE = 'DELETE_NOTE';

export default {
  GET_NOTE_TYPES,
  GET_LABELS,
  GET_INSPIRATIONS,
  GET_NOTES,
  CREATE_NOTE,
  EDIT_NOTE,
  DELETE_NOTE,
};
